# Generated by Django 4.2.2 on 2023-06-20 08:30

import backend.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid1)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Please enter a valid email address in the format"
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Please provide a valid email address.",
                                regex="^name@name.name",
                            ),
                        ],
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("other_names", models.CharField(blank=True, max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("birth_date", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non-Binary", "Non-Binary"),
                            ("Prefer Not To Say", "Prefer Not To Say"),
                        ],
                        default="Prefer Not To Say",
                        max_length=20,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="password",
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=8,
                                message="Please ensure the password is at least 8 characters",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Please use a different password",
                                regex="^password",
                            ),
                        ],
                    ),
                ),
                ("is_housekeeper", models.BooleanField(default=False)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.family"
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_father",
                        to="backend.member",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children_mother",
                        to="backend.member",
                    ),
                ),
                ("spouse_of", models.ManyToManyField(blank=True, to="backend.member")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.member"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.family"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=backend.models.get_upload_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="backend.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="family",
            name="founder",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="founded_family",
                to="backend.member",
            ),
        ),
    ]
