# Generated by Django 4.2.2 on 2023-06-20 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="last_logged",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
