# Generated by Django 4.2.2 on 2023-06-18 15:42

import backend.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_member_child_of_remove_member_is_founder_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="family",
            managers=[
                ("objects", backend.models.FamilyManager()),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="is_housekeeper",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid1, primary_key=True, serialize=False
            ),
        ),
    ]
