# Generated by Django 4.2.2 on 2023-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_family_managers_member_is_housekeeper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
